import { DistributiveOmit, Question } from './types';
import { KARTING_WINNER_GROUP, KARTING_LOSER_GROUP } from './karting';
import { DINNER_HEAD, DINNER_LEFT, DINNER_RIGHT, DINNER_CORRECT_PRIMO, DINNER_CORRECT_SECONDO } from './dinner';
import { HAM_ROWS } from './ham';
import { BOWIE_MARKS, BOWIE_ASPECT_RATIO } from './bowie';
import { RUBEN_MENU, RUBEN_OPTIONS, RUBEN_CORRECT_INDEX } from './ruben';
import { TRAVEL_MAP_URL, TRAVEL_MAP_ASPECT_RATIO, TRAVEL_LANDMARKS, TRAVEL_STOPS, TRAVEL_CORRECT_GROUPS } from './travel';

// Kept in the same order as Vragen.txt so the running order matches what's
// planned there.
export const sampleQuestions: DistributiveOmit<Question, 'id'>[] = [
  {
    type: 'multiple_choice',
    title: 'The Lake',
    text: 'Which story is based on the area around the ice cold swimming lake?',
    options: ['Pinocchio', 'Narnia', 'Alice in Wonderland', 'The Wizard of Oz'],
    correctIndex: 1,
    timeLimitSec: 20,
    points: 1000,
  },
  {
    type: 'multi_select',
    title: 'Assisi',
    text: 'Which saint(s) do we associate with the town of Assisi? Select all that apply.',
    options: [
      'St. Francis',
      'St. Anthony',
      'St. Carlo',
      'St. Clare',
      'St. Catherine',
      'St. Nicholas',
      'St. Peter',
    ],
    correctIndexes: [0, 2, 3],
    timeLimitSec: 30,
    points: 1500,
  },
  {
    type: 'drag_count',
    title: 'Pedro',
    text: "How many times does the word \"Pedro\" appear in Raffaella Carra's song \"Pedro\"?",
    dragLabel: 'Pedro',
    correctCount: 48,
    timeLimitSec: 45,
    points: 1500,
  },
  {
    type: 'multiple_choice',
    title: 'Pool Party',
    text: 'How many liters of water did the pool lose after the first pool party?',
    options: ['30 liters', '300 liters', '3000 liters', '30.000 liters'],
    correctIndex: 2,
    timeLimitSec: 20,
    points: 1000,
  },
  {
    type: 'podium_order',
    title: 'Karting',
    text: 'Who finished where in karting? Put both groups in the right order.',
    correctOrder: [KARTING_WINNER_GROUP, KARTING_LOSER_GROUP],
    groupLabels: ['Winner group', 'Loser group'],
    timeLimitSec: 90,
    points: 2000,
  },
  {
    type: 'ham_cut',
    title: 'Ham cutting',
    text: 'Drag the two points to find the line that cuts the ham exactly in half.',
    imageUrl: '/images/ham.jpg',
    rows: HAM_ROWS,
    timeLimitSec: 45,
    points: 1500,
  },
  {
    type: 'plate_assignment',
    title: 'Primo / Secondo',
    text: 'At the final dinner, who had a primo, who had a secondo, and who had both?',
    head: DINNER_HEAD,
    left: DINNER_LEFT,
    right: DINNER_RIGHT,
    correctPrimo: DINNER_CORRECT_PRIMO,
    correctSecondo: DINNER_CORRECT_SECONDO,
    timeLimitSec: 90,
    points: 2000,
  },
  {
    type: 'trace_marks',
    title: "Bowie's scratches",
    text: "Everyone fell into the pool at the pool party. Everyone? No, one friend was able to resist any attempt. But he paid dearly. Draw as best as you can the marks on Bowie's side from the pool party",
    playerText: 'Draw the scratches as best as you can',
    imageUrl: '/images/bowie-nomarks.jpeg',
    revealImageUrl: '/images/bowie-marks.jpg',
    aspectRatio: BOWIE_ASPECT_RATIO,
    marks: BOWIE_MARKS,
    timeLimitSec: 60,
    points: 1500,
  },
  {
    type: 'multiple_choice',
    title: 'Cena da Ruben',
    text: "You're at an Italian restaurant and you want to have a nice meal. The problem: you are Ruben, and therefore gluten intolerant. What do you pick?",
    playerText: "You are Ruben, and you're gluten intolerant. What do you order?",
    options: RUBEN_OPTIONS,
    correctIndex: RUBEN_CORRECT_INDEX,
    menu: RUBEN_MENU,
    timeLimitSec: 45,
    points: 1000,
  },
  {
    type: 'multiple_choice',
    title: 'Village festival',
    text: 'At the village festival, we arrived when the number was at 182. Which number did we have?',
    imageUrl: '/images/festival.jpg',
    options: ['190', '256', '360', '472'],
    correctIndex: 2,
    timeLimitSec: 20,
    points: 1000,
  },
  {
    type: 'multiple_choice',
    title: 'The swimming pool',
    text: 'What was the reason the swimming pool was where it was?',
    options: [
      'Easy jumping off the wall',
      "Out of the way for Pietro's wife, so it wouldn't get too noisy",
      'It was a septic tank',
      'Who knowah? Is Italia, we puttah the swimming pool where we wantah!',
    ],
    correctIndex: 2,
    timeLimitSec: 20,
    points: 1000,
  },
  {
    type: 'travel_map',
    title: 'On the way',
    text: 'Drag each person to how they _arrived_ to Perugia',
    mapUrl: TRAVEL_MAP_URL,
    aspectRatio: TRAVEL_MAP_ASPECT_RATIO,
    landmarks: TRAVEL_LANDMARKS,
    stops: TRAVEL_STOPS,
    correctGroups: TRAVEL_CORRECT_GROUPS,
    timeLimitSec: 120,
    points: 2000,
  },
  {
    type: 'multiple_choice',
    title: 'Perusia',
    text: 'What people used to live in Perugia before Octavian burnt their terracotta asses?',
    options: ['Peruvians', 'Umbrians', 'Etruscans', 'Sabines'],
    correctIndex: 2,
    timeLimitSec: 20,
    points: 1000,
  },
];
